# Generated by Django 5.0.2 on 2024-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seen',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('seen', 'Seen')], default='pending', max_length=10),
        ),
    ]
